# Workflow name (must be in capital letter) and step_id (id from station_steps table) are very important
filter_steps:
  LDP:
    - step_name: IA Approval – IA Approved
      step_id: 1
    - step_name: ECR – INBOX  
      step_id: 7
    - step_name: Collaboration – Sent to Collab.  
      step_id: 5
    - step_name: CRB – CRB Started  
      step_id: 17
    - step_name: CRB – ECR Released  
      step_id: 18

  ETA:
    - step_name: Step 3 (L2)
      step_id: 22
    - step_name: Step 8 (L3)
      step_id: 25
    - step_name: Step 11 (L3) 
      step_id: 28
    - step_name: Step 4 (L2)
      step_id: 31